name: Build macOS

on: 
  workflow_call:
    secrets:
      MACOS_CERT:
        required: true
      MACOS_CERT_PWD:
        required: true
      APP_STORE_CONNECT_ISSUER_ID:
        required: true
      APP_STORE_CONNECT_KEY_IDENTIFIER:
        required: true
      APP_STORE_CONNECT_PRIVATE_KEY:
        required: true
      

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          architecture: x64
          channel: stable
          cache: true
          cache-key: ${{runner.os}}-flutter-cache-2.10.x
      - name: Install codemagic-cli
        run: pip3 install codemagic-cli-tools
      - uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{runner.os}}-flutter-cache-2.10.x
      - run: flutter pub get
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos --release
      - name: Install certificates
        env: 
          CERT: ${{secrets.MACOS_CERT}}
          P12_PASSWORD: ${{secrets.MACOS_CERT_PWD}}
          KEYCHAIN_PASSWORD: 'localkeychainosefunpeu'
          APP_STORE_CONNECT_ISSUER_ID: ${{secrets.APP_STORE_CONNECT_ISSUER_ID}}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{secrets.APP_STORE_CONNECT_KEY_IDENTIFIER}}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{secrets.APP_STORE_CONNECT_PRIVATE_KEY}}
        run: |
          APP_NAME=$(find $(pwd) -name "*.app")
          PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          CERTIFICATE_KEY=$RUNNER_TEMP/cert_key
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n $CERT | base64 --decode --output $CERTIFICATE_PATH

          openssl pkcs12 -in $CERTIFICATE_PATH -password pass:$P12_PASSWORD -nodes -nocerts | openssl rsa -out $CERTIFICATE_KEY

          app-store-connect fetch-signing-files fr.avekia.avekiatestci \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --certificate-key=@file:$CERTIFICATE_KEY \
            --create

          app-store-connect create-certificate \
            --type MAC_INSTALLER_DISTRIBUTION \
            --certificate-key=@file:$CERTIFICATE_KEY \
            --save

          app-store-connect list-certificates \
            --type MAC_INSTALLER_DISTRIBUTION \
            --certificate-key=@file:$CERTIFICATE_KEY \
            --save

          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

          # build
          xcrun productbuild --component "$APP_NAME" /Applications/ TestCIAppUnsigned.pkg
          # | contains("Mac Developer Installer"))
          INSTALLER_CERT_NAME=$(keychain list-certificates \
                    | jq '.[0]
                      | select(.common_name
                      | contains("Mac Developer Installer"))
                      | .common_name' \
                    | xargs)
          echo "cert"
          echo $INSTALLER_CERT_NAME
          echo "cert2"
          xcrun productsign --sign "$INSTALLER_CERT_NAME" TestCIAppUnsigned.pkg TestCIApp.pkg
          rm -f TestCIAppUnsigned.pkg
          app-store-connect publish \
            --path "$PACKAGE_NAME"

      - name : Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-macos
          path: build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: TestCIApp.pkg