name: Build iOS

on: workflow_call

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          architecture: x64
          channel: stable
          cache: true
          cache-key: ${{runner.os}}-flutter-cache-2.10.x
      - uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{runner.os}}-flutter-cache-2.10.x
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: |
          xcrun productbuild --component build/ios/iphoneos/Runner.app /Applications/ TestCIApp.pkg
# APP_NAME=$(find $(pwd) -name "*.app")
# PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
# SWAGGY UNCOMMENTED LINE HERE
# INSTALLER_CERT_NAME=$(keychain list-certificates \
#           | jq '.[0]
#             | select(.common_name
#             | contains("Mac Developer Installer"))
#             | .common_name' \
#           | xargs)
# xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"
# rm -f unsigned.pkg 
      - name : Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-ios
          path: build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: TestCIApp.pkg