name: Build android

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.x'
        architecture: x64
        channel: stable
        cache: true
        cache-key: ${{runner.os}}-flutter-cache-2.10.x
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - name : Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-android
        path: build