name: Build apps

on:
  push:
    tags:
      - v*

jobs:
  macos:
    uses: ./.github/workflows/_build-macos.yml

  # iphoneos:
  #   uses: ./.github/workflows/_build-iphoneos.yml

  windows:
    uses: ./.github/workflows/_build-windows.yml

  android:
    uses: ./.github/workflows/_build-android.yml
    
