name: Build apps

on:
  push:
    tags:
      - v*

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        architecture: x64
    - uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{runner.os}}-flutter-cache-${{env.flutter_version}}
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign
    #- run: ls ./build/ios/
    #- run: echo "#####"
    #- run: ls ./build/ios/iphoneos
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/ios/iphoneos/Runner.app

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
      - uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{runner.os}}-flutter-cache-${{env.flutter_version}}
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: test-ci-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      - run: tree ./build/windows/runner/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: test-ci-${{github.ref_name}}-windows.zip

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
    - uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{runner.os}}-flutter-cache-${{env.flutter_version}}
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
    - run: tree ./build/app
    
