name: Build and deploy apps

on:
  push:
    tags:
      - v*
      - '!v*-rc*'

jobs:
  macos:
    uses: ./.github/workflows/_build-macos.yml
    secrets: inherit
    with:
      deploy: true

  iphoneos:
    uses: ./.github/workflows/_build-iphoneos.yml
    secrets: inherit
    with:
      deploy: true

  # windows:
  #   uses: ./.github/workflows/_build-windows.yml

  # android:
  #   uses: ./.github/workflows/_build-android.yml
    
