name: Build ios

on:
  push:
    tags:
      - v*

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        architecture: x64
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign
    - run: ls && cd ./ios && ls
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: ./build/ios/iphoneos/Runner.app