name: Build windows

on:
  push:
    tags:
      - v*

jobs:
 build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: ls ./build/windows/x64/Release
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: ./windows/build/runner/Release/test_ci_app.exe