name: Deploy apps

on:
  deployment:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy-macos:
    uses: ./.github/workflows/_build-macos.yml
    secrets: inherit
    with:
      deploy: true

  deploy-iphoneos:
    uses: ./.github/workflows/_build-iphoneos.yml
    secrets: inherit
    with:
      deploy: true

  # windows:
  #   uses: ./.github/workflows/_build-windows.yml

  # android:
  #   uses: ./.github/workflows/_build-android.yml
    
  deployment-cooloff:
    needs: [deploy-macos, deploy-iphoneos]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          state: "success"
          deployment_id: ${{ github.event.deployment.id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          state: "failure"
          deployment_id: ${{ github.event.deployment.id }}