name: Deploy apps

on:
  deployment:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy-macos:
    uses: ./.github/workflows/_build-macos.yml
    secrets: inherit
    with:
      deploy: true

  deploy-iphoneos:
    uses: ./.github/workflows/_build-iphoneos.yml
    secrets: inherit
    with:
      deploy: true

  # windows:
  #   uses: ./.github/workflows/_build-windows.yml

  # android:
  #   uses: ./.github/workflows/_build-android.yml
    
