name: Deploy apps

on:
  deployment:

# concurrency:
#   group: production
#   cancel-in-progress: true

jobs:
  deploy-macos:
    name: Deploy MacOS
    uses: ./.github/workflows/_build-macos.yml
    secrets: inherit
    with:
      deploy: true
      environment: production

  deploy-iphoneos:
    name: Deploy iOS
    uses: ./.github/workflows/_build-iphoneos.yml
    secrets: inherit
    with:
      deploy: true
      environment: production

  # windows:
  #   uses: ./.github/workflows/_build-windows.yml

  # android:
  #   uses: ./.github/workflows/_build-android.yml
    
  post-deployment-success:
    name: Deployment success
    needs: [deploy-macos, deploy-iphoneos]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Update deployment status (success)
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          state: "success"
          deployment_id: ${{ github.event.deployment.id }}

  post-deployment-failure:
    name: Deployment failure
    needs: [deploy-macos, deploy-iphoneos]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Update deployment status (failure)
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          state: "failure"
          deployment_id: ${{ github.event.deployment.id }}
