name: Build iOS

on: workflow_call

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        architecture: x64
    - uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{runner.os}}-flutter-cache-${{env.flutter_version}}
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign
    - run: ls build/ios/iphoneos/
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: build/ios/iphoneos/Runner.app