name: Build and prepare deploys

on:
  push:
    tags:
      - v*

jobs:
  macos:
    name: Build MacOS
    uses: ./.github/workflows/_build-macos.yml
    secrets: inherit

  iphoneos:
    name: Build iOS
    uses: ./.github/workflows/_build-iphoneos.yml
    secrets: inherit

  # windows:
  #   uses: ./.github/workflows/_build-windows.yml

  # android:
  #   uses: ./.github/workflows/_build-android.yml

  create-deployments:
    name: Create deployment request
    needs: [macos, iphoneos]
    runs-on: ubuntu-latest
    steps:
      - name: Get Token for actions
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        with:
          token: "${{ env.GITHUB_TOKEN }}"
          environment: production
          description: "${{ github.event.head_commit.message }}"
      

    
