name: Deployer test

concurrency:
  group: production
  cancel-in-progress: true

on:
  deployment:


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - run: echo "Deploying ??"

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - run: qnsdfciundscfnsoicf

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          state: "success"
          deployment_id: ${{ github.event.deployment.id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          state: "failure"
          deployment_id: ${{ github.event.deployment.id }}