name: Build Windows

on: workflow_call

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          architecture: x64
          channel: stable
          cache: true
          cache-key: ${{runner.os}}-flutter-cache-2.10.x
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - run: flutter pub run msix:create --install-certificate false
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: test-ci-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      - name : Publish
        uses: actions/upload-artifact@v3
        with:
          name: release-windows
          path: build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            ./build/windows/runner/Release/test_ci_app.msix
            ./build/windows/runner/Release/test-ci-${{github.ref_name}}-windows.zip